create unique index if not exists materials_slug_key on public.materials(slug);

insert into public.materials (
  slug,
  name,
  category,
  status,
  featured,
  sort_order,
  main_image,
  short_description,
  long_description,
  color,
  finish,
  recommended_use,
  resistance,
  maintenance,
  whatsapp_message,
  seo_title,
  seo_description
)
values
(
  'cuarzo-beige',
  'Cuarzo Beige',
  'Cuarzo',
  'published',
  true,
  1,
  '/images/catalogo/cuarzo-beige.jpg',
  'Cuarzo Beige para mesadas, cocinas, baños y superficies a medida.',
  'Cuarzo Beige es una opción de cuarzo seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Beige',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Cuarzo Beige. ¿Me pueden asesorar?',
  'Cuarzo Beige para mesadas y superficies | Marmolería Pietra',
  'Cotizá Cuarzo Beige para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'cuarzo-blanco-estelar',
  'Cuarzo Blanco Estelar',
  'Cuarzo',
  'published',
  true,
  2,
  '/images/catalogo/cuarzo-blanco-estelar.svg',
  'Cuarzo Blanco Estelar para mesadas, cocinas, baños y superficies a medida.',
  'Cuarzo Blanco Estelar es una opción de cuarzo seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Blanco',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Cuarzo Blanco Estelar. ¿Me pueden asesorar?',
  'Cuarzo Blanco Estelar para mesadas y superficies | Marmolería Pietra',
  'Cotizá Cuarzo Blanco Estelar para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'cuarzo-gris',
  'Cuarzo Gris',
  'Cuarzo',
  'published',
  true,
  3,
  '/images/catalogo/cuarzo-gris.jpg',
  'Cuarzo Gris para mesadas, cocinas, baños y superficies a medida.',
  'Cuarzo Gris es una opción de cuarzo seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Gris',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Cuarzo Gris. ¿Me pueden asesorar?',
  'Cuarzo Gris para mesadas y superficies | Marmolería Pietra',
  'Cotizá Cuarzo Gris para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'cuarzo-negro',
  'Cuarzo Negro',
  'Cuarzo',
  'published',
  true,
  4,
  '/images/catalogo/cuarzo-negro.jpg',
  'Cuarzo Negro para mesadas, cocinas, baños y superficies a medida.',
  'Cuarzo Negro es una opción de cuarzo seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Negro',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Cuarzo Negro. ¿Me pueden asesorar?',
  'Cuarzo Negro para mesadas y superficies | Marmolería Pietra',
  'Cotizá Cuarzo Negro para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'cuarzo-rojo',
  'Cuarzo Rojo',
  'Cuarzo',
  'published',
  false,
  5,
  '/images/catalogo/cuarzo-rojo.jpg',
  'Cuarzo Rojo para mesadas, cocinas, baños y superficies a medida.',
  'Cuarzo Rojo es una opción de cuarzo seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Rojo',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Cuarzo Rojo. ¿Me pueden asesorar?',
  'Cuarzo Rojo para mesadas y superficies | Marmolería Pietra',
  'Cotizá Cuarzo Rojo para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'cuarzo-verde-claro',
  'Cuarzo Verde Claro',
  'Cuarzo',
  'published',
  false,
  6,
  '/images/catalogo/cuarzo-verde-claro.jpg',
  'Cuarzo Verde Claro para mesadas, cocinas, baños y superficies a medida.',
  'Cuarzo Verde Claro es una opción de cuarzo seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Verde claro',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Cuarzo Verde Claro. ¿Me pueden asesorar?',
  'Cuarzo Verde Claro para mesadas y superficies | Marmolería Pietra',
  'Cotizá Cuarzo Verde Claro para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'blanco-dallas',
  'Blanco Dallas',
  'Granito',
  'published',
  true,
  7,
  '/images/catalogo/granito-blanco-dallas.jpg',
  'Blanco Dallas para mesadas, cocinas, baños y superficies a medida.',
  'Blanco Dallas es una opción de granito seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Blanco',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Blanco Dallas. ¿Me pueden asesorar?',
  'Blanco Dallas para mesadas y superficies | Marmolería Pietra',
  'Cotizá Blanco Dallas para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'blanco-di-capri',
  'Blanco Di Capri',
  'Granito',
  'published',
  true,
  8,
  '/images/catalogo/granito-blanco-di-capri.jpg',
  'Blanco Di Capri para mesadas, cocinas, baños y superficies a medida.',
  'Blanco Di Capri es una opción de granito seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Blanco',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Blanco Di Capri. ¿Me pueden asesorar?',
  'Blanco Di Capri para mesadas y superficies | Marmolería Pietra',
  'Cotizá Blanco Di Capri para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'blanco-itaunas',
  'Blanco Itaúnas',
  'Granito',
  'published',
  true,
  9,
  '/images/catalogo/granito-blanco-itaunas.jpg',
  'Blanco Itaúnas para mesadas, cocinas, baños y superficies a medida.',
  'Blanco Itaúnas es una opción de granito seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Blanco',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Blanco Itaúnas. ¿Me pueden asesorar?',
  'Blanco Itaúnas para mesadas y superficies | Marmolería Pietra',
  'Cotizá Blanco Itaúnas para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'cafe-imperial',
  'Café Imperial',
  'Granito',
  'published',
  true,
  10,
  '/images/catalogo/granito-cafe-imperial.jpg',
  'Café Imperial para mesadas, cocinas, baños y superficies a medida.',
  'Café Imperial es una opción de granito seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Café',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Café Imperial. ¿Me pueden asesorar?',
  'Café Imperial para mesadas y superficies | Marmolería Pietra',
  'Cotizá Café Imperial para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'gris-corumba',
  'Gris Corumbá',
  'Granito',
  'published',
  true,
  11,
  '/images/catalogo/granito-gris-corumba.jpg',
  'Gris Corumbá para mesadas, cocinas, baños y superficies a medida.',
  'Gris Corumbá es una opción de granito seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Gris',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Gris Corumbá. ¿Me pueden asesorar?',
  'Gris Corumbá para mesadas y superficies | Marmolería Pietra',
  'Cotizá Gris Corumbá para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'negro-san-gabriel',
  'Negro San Gabriel',
  'Granito',
  'published',
  true,
  12,
  '/images/catalogo/granito-negro-san-gabriel.jpg',
  'Negro San Gabriel para mesadas, cocinas, baños y superficies a medida.',
  'Negro San Gabriel es una opción de granito seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Negro',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Negro San Gabriel. ¿Me pueden asesorar?',
  'Negro San Gabriel para mesadas y superficies | Marmolería Pietra',
  'Cotizá Negro San Gabriel para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'verde-ubatuba',
  'Verde Ubatuba',
  'Granito',
  'published',
  true,
  13,
  '/images/catalogo/granito-verde-ubatuba.jpg',
  'Verde Ubatuba para mesadas, cocinas, baños y superficies a medida.',
  'Verde Ubatuba es una opción de granito seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Verde oscuro',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Verde Ubatuba. ¿Me pueden asesorar?',
  'Verde Ubatuba para mesadas y superficies | Marmolería Pietra',
  'Cotizá Verde Ubatuba para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'marmol-blanco',
  'Mármol Blanco',
  'Mármol',
  'published',
  false,
  14,
  '/images/catalogo/marmol-blanco.jpg',
  'Mármol Blanco para mesadas, cocinas, baños y superficies a medida.',
  'Mármol Blanco es una opción de mármol seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Blanco',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Uso decorativo interior con cuidado adecuado.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Mármol Blanco. ¿Me pueden asesorar?',
  'Mármol Blanco para mesadas y superficies | Marmolería Pietra',
  'Cotizá Mármol Blanco para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'marmol-travertino',
  'Mármol Travertino',
  'Mármol',
  'published',
  false,
  15,
  '/images/catalogo/marmol-travertino.jpg',
  'Mármol Travertino para mesadas, cocinas, baños y superficies a medida.',
  'Mármol Travertino es una opción de mármol seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Travertino',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Uso decorativo interior con cuidado adecuado.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Mármol Travertino. ¿Me pueden asesorar?',
  'Mármol Travertino para mesadas y superficies | Marmolería Pietra',
  'Cotizá Mármol Travertino para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'marron-emperador',
  'Marrón Emperador',
  'Mármol',
  'published',
  false,
  16,
  '/images/catalogo/marron-emperador.jpg',
  'Marrón Emperador para mesadas, cocinas, baños y superficies a medida.',
  'Marrón Emperador es una opción de mármol seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Marrón',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Uso decorativo interior con cuidado adecuado.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Marrón Emperador. ¿Me pueden asesorar?',
  'Marrón Emperador para mesadas y superficies | Marmolería Pietra',
  'Cotizá Marrón Emperador para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'neolith-calacatta',
  'Neolith Calacatta',
  'Sinterizado',
  'published',
  true,
  17,
  '/images/catalogo/neolith-calacatta.jpg',
  'Neolith Calacatta para mesadas, cocinas, baños y superficies a medida.',
  'Neolith Calacatta es una opción de sinterizado seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Blanco con vetas',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Neolith Calacatta. ¿Me pueden asesorar?',
  'Neolith Calacatta para mesadas y superficies | Marmolería Pietra',
  'Cotizá Neolith Calacatta para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
),
(
  'piedra-traslucida',
  'Piedra Traslúcida',
  'Especial',
  'published',
  false,
  18,
  '/images/catalogo/piedra-traslucida.jpg',
  'Piedra Traslúcida para mesadas, cocinas, baños y superficies a medida.',
  'Piedra Traslúcida es una opción de especial seleccionada para proyectos residenciales y comerciales que buscan buena presencia visual, resistencia y terminación profesional.',
  'Traslúcido',
  'Pulido',
  'Cocinas, baños, mesadas, barras, quinchos y revestimientos.',
  'Alta resistencia para uso residencial y comercial.',
  'Limpieza con paño húmedo y productos neutros.',
  'Hola Pietra, quiero cotizar el material Piedra Traslúcida. ¿Me pueden asesorar?',
  'Piedra Traslúcida para mesadas y superficies | Marmolería Pietra',
  'Cotizá Piedra Traslúcida para cocinas, baños, mesadas y superficies a medida con Marmolería Pietra.'
)
on conflict (slug) do update set
  name = excluded.name,
  category = excluded.category,
  status = excluded.status,
  featured = excluded.featured,
  sort_order = excluded.sort_order,
  main_image = excluded.main_image,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  color = excluded.color,
  finish = excluded.finish,
  recommended_use = excluded.recommended_use,
  resistance = excluded.resistance,
  maintenance = excluded.maintenance,
  whatsapp_message = excluded.whatsapp_message,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  updated_at = now();
